VICENTE RODRIGUEZ JUAREZ, DAVID ADAN JIMENEZ TORREZ, EDGAR LEONARDO MOCTEZUMA DEBO
# Analítica de Datos — Tema 1: Preprocesamiento de datos  
## Notebook evaluativa

**Asignatura:** Analítica de Datos (IAD-2403)  
**Tema:** Preprocesamiento de datos  
**Herramientas permitidas:** NumPy, Pandas  
**Duración sugerida:** 45-50 minutos

### Instrucciones generales
1. Ejecuta en orden.
2. Responde en las celdas marcadas como **Respuesta del estudiante**.
3. No borres evidencias de salida.
4. Guarda tu archivo como: `Apellido_Nombre_Eval_Tema1_Preprocesamiento.ipynb`

In [69]:
print(f"df_limpio tiene {df_limpio.shape[0]} registros y {df_limpio.shape[1]} columnas.")

df_limpio tiene 11 registros y 12 columnas.

## Rúbrica (100 puntos)
- **A. Importación e inspección inicial** (15)
- **B. Detección de errores de calidad** (20)
- **C. Limpieza y tratamiento** (25)
- **D. Filtración y transformación** (20)
- **E. Fusión (`merge`) y resumen final** (15)
- **F. Presentación y claridad** (5)

## 0) Preparación del entorno (no modificar)

In [71]:
import numpy as np
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

print("Entorno listo ✅")
print("Pandas:", pd.__version__)
print("NumPy :", np.__version__)

Entorno listo ✅
Pandas: 2.2.2
NumPy : 2.0.2

## 1) Generación del dataset de evaluación (no modificar)

Se crearán:
- `evaluacion_datos/estudiantes_crudo_eval.csv`
- `evaluacion_datos/apoyos_eval.csv`

In [72]:
Path("evaluacion_datos").mkdir(exist_ok=True)

df_crudo_eval = pd.DataFrame({
    "id_estudiante": [201,202,203,204,205,206,207,208,209,210,211,211],
    "nombre": ["Laura","Iván","María","Diego","Sofía","Raúl","Carmen","Joel","Paola","Andrés","Karla","Karla"],
    "edad": [19, 20, np.nan, 22, 21, 19, 20, 23, 21, 20, 22, 22],
    "campus": ["SLP Centro", "slp centro ", "SLP Norte", "SLP Cntro", "Matehuala", "SLP Norte", "Matehuala", "SLP Centro", "SLP Norte", "SLP Centro", "SLP centro", "SLP centro"],
    "modalidad": ["Escolarizada", "escolar", "Mixta", "MIXTA ", "Escolarizada", "Mixta", "Mixta", "Escolarizada", "Escolarizada", "Escolarizada", "Mixta", "Mixta"],
    "promedio": [87, 92, 75, np.nan, 83, 104, 68, 71, 95, 79, 88, 88],
    "asistencia_pct": [93, 86, 80, 88, np.nan, 91, 74, 77, 98, 102, 85, 85],
    "creditos_inscritos": [30, 32, 28, 30, 26, 30, 24, 30, 32, 28, 30, 30],
    "creditos_aprobados": [29, 31, 27, 29, 25, 33, 22, 28, 31, 28, 30, 30]
})

df_apoyos_eval = pd.DataFrame({
    "id_estudiante": [201,203,204,206,208,209,212],
    "beca": ["Sí","No","Sí","No","Sí","No","Sí"],
    "tutoria_horas_mes": [3, 0, 2, 1, 4, 0, 2]
})

df_crudo_eval.to_csv("evaluacion_datos/estudiantes_crudo_eval.csv", index=False)
df_apoyos_eval.to_csv("evaluacion_datos/apoyos_eval.csv", index=False)

print("Archivos creados ✅")
display(df_crudo_eval.head())

Archivos creados ✅

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

# Actividad A. Importación e inspección inicial (15 puntos)

**Instrucciones**
1. Importa ambos CSV en `df` y `apoyos`.
2. Muestra: `shape`, `head()`, `info()`, `describe()`.
3. Escribe una respuesta breve:
   - identificador
   - columnas categóricas

In [73]:
# Respuesta del estudiante (A1)
# Importa ambos CSV en df y apoyos.
df = pd.read_csv("evaluacion_datos/estudiantes_crudo_eval.csv")
apoyos = pd.read_csv("evaluacion_datos/apoyos_eval.csv")

In [74]:
# --- Respuesta del estudiante (A2) ---
# Muestra shape, head, info y describe
# --- Respuesta del estudiante (A2) ---
# Muestra: shape, head(), info(), describe().

print("--- DataFrame 'df' ---")
print("Shape:", df.shape)
display(df.head())
df.info()
display(df.describe(include='all'))

print("\n--- DataFrame 'apoyos' ---")
print("Shape:", apoyos.shape)
display(apoyos.head())
apoyos.info()
display(apoyos.describe(include='all'))

--- DataFrame 'df' ---
Shape: (12, 9)

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_estudiante       12 non-null     int64
 1   nombre              12 non-null     object
 2   edad                11 non-null     float64
 3   campus              12 non-null     object
 4   modalidad           12 non-null     object
 5   promedio            11 non-null     float64
 6   asistencia_pct      11 non-null     float64
 7   creditos_inscritos  12 non-null     int64
 8   creditos_aprobados  12 non-null     int64
dtypes: float64(3), int64(3), object(3)
memory usage: 996.0+ bytes

        id_estudiante nombre       edad      campus     modalidad    promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
count       12.000000     12  11.000000          12            12   11.000000       11.000000           12.000000           12.000000
unique            NaN     11        NaN           6             4         NaN             NaN                 NaN                 NaN
top               NaN  Karla        NaN  SLP Centro  Escolarizada         NaN             NaN                 NaN                 NaN
freq              NaN      2        NaN           3             5         NaN             NaN                 NaN                 NaN
mean       206.416667    NaN  20.818182         NaN           NaN   84.545455       87.181818           29.166667           28.583333
std          3.476109    NaN   1.328020         NaN           NaN   10.745824        8.518429            2.329000            2.937480
min        201.000000    NaN  19.000000         NaN           NaN   68.000000       74.000000           24.000000           22.000000
25%        203.750000    NaN  20.000000         NaN           NaN   77.000000       82.500000           28.000000           27.750000
50%        206.500000    NaN  21.000000         NaN           NaN   87.000000       86.000000           30.000000           29.000000
75%        209.250000    NaN  22.000000         NaN           NaN   90.000000       92.000000           30.000000           30.250000
max        211.000000    NaN  23.000000         NaN           NaN  104.000000      102.000000           32.000000           33.000000

--- DataFrame 'apoyos' ---
Shape: (7, 3)

   id_estudiante beca  tutoria_horas_mes
0            201   Sí                  3
1            203   No                  0
2            204   Sí                  2
3            206   No                  1
4            208   Sí                  4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_estudiante      7 non-null      int64
 1   beca               7 non-null      object
 2   tutoria_horas_mes  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

        id_estudiante beca  tutoria_horas_mes
count        7.000000    7           7.000000
unique            NaN    2                NaN
top               NaN   Sí                NaN
freq              NaN    4                NaN
mean       206.142857  NaN           1.714286
std          3.804759  NaN           1.496026
min        201.000000  NaN           0.000000
25%        203.500000  NaN           0.500000
50%        206.000000  NaN           2.000000
75%        208.500000  NaN           2.500000
max        212.000000  NaN           4.000000

### Respuesta breve del estudiante (A3)
- Identificador: `id_estudiante` para ambos DataFrames.
- Columnas categóricas:
  - En `df`: `nombre`, `campus`, `modalidad`.
  - En `apoyos`: `beca`.

# Actividad B. Detección de errores de calidad (20 puntos)

Detecta en `df`:
1. Faltantes por columna
2. Duplicados por `id_estudiante`
3. Valores únicos de `campus` y `modalidad`
4. Fuera de rango (`promedio`, `asistencia_pct`)
5. Error lógico (`creditos_aprobados > creditos_inscritos`)

In [75]:
# --- Respuesta del estudiante (B1) ---
# Valores faltantes por columna
print("Valores faltantes en df:")
display(df.isnull().sum())

Valores faltantes en df:

id_estudiante         0
nombre                0
edad                  1
campus                0
modalidad             0
promedio              1
asistencia_pct        1
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

In [76]:
# --- Respuesta del estudiante (B2) ---
# Duplicados por id_estudiante
print("Filas duplicadas por 'id_estudiante':")
duplicated_ids = df[df.duplicated(subset=['id_estudiante'], keep=False)].sort_values(by='id_estudiante')
display(duplicated_ids)
print(f"Total de filas duplicadas (incluyendo la primera aparición): {len(duplicated_ids)}")

Filas duplicadas por 'id_estudiante':

    id_estudiante nombre  edad      campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
10            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30
11            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30

Total de filas duplicadas (incluyendo la primera aparición): 2

In [77]:
print("Valores únicos para 'campus':")
display(df['campus'].unique())

print("\nValores únicos para 'modalidad':")
display(df['modalidad'].unique())

Valores únicos para 'campus':

array(['SLP Centro', 'slp centro ', 'SLP Norte', 'SLP Cntro', 'Matehuala',
       'SLP centro'], dtype=object)

Valores únicos para 'modalidad':

array(['Escolarizada', 'escolar', 'Mixta', 'MIXTA '], dtype=object)

In [78]:
print("Valores de 'promedio' fuera de rango (0-100):")
display(df[(df['promedio'] < 0) | (df['promedio'] > 100)])

print("\nValores de 'asistencia_pct' fuera de rango (0-100):")
display(df[(df['asistencia_pct'] < 0) | (df['asistencia_pct'] > 100)])

Valores de 'promedio' fuera de rango (0-100):

   id_estudiante nombre  edad     campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
5            206   Raúl  19.0  SLP Norte     Mixta     104.0            91.0                  30                  33

Valores de 'asistencia_pct' fuera de rango (0-100):

   id_estudiante  nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
9            210  Andrés  20.0  SLP Centro  Escolarizada      79.0           102.0                  28                  28

In [79]:
print("Error lógico: 'creditos_aprobados' > 'creditos_inscritos':")
display(df[df['creditos_aprobados'] > df['creditos_inscritos']])

Error lógico: 'creditos_aprobados' > 'creditos_inscritos':

   id_estudiante nombre  edad     campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
5            206   Raúl  19.0  SLP Norte     Mixta     104.0            91.0                  30                  33

### Respuesta breve del estudiante (B6)
Menciona al menos 3 problemas que encontraste:
- Inconsistencia en valores categóricos (ej. 'campus' y 'modalidad' con diferentes grafías, mayúsculas/minúsculas y espacios).
- Valores numéricos fuera de rango (ej. 'promedio' y 'asistencia_pct' mayores a 100).
- Error lógico donde 'creditos_aprobados' es mayor que 'creditos_inscritos'.
- Valores faltantes (ej. 'edad', 'promedio', 'asistencia_pct').
- Filas duplicadas basadas en 'id_estudiante'.

# Actividad C. Limpieza y tratamiento de errores (25 puntos)

Crea `df_limpio` y realiza:
1. Limpieza de texto (`campus`, `modalidad`)
2. Normalización de etiquetas (ej. `slp centro`, `SLP Cntro`, `escolar`, `MIXTA`)
3. Eliminar duplicados por `id_estudiante`
4. Corregir rangos en `promedio` y `asistencia_pct` (0–100)
5. Corregir `creditos_aprobados <= creditos_inscritos`
6. Imputar faltantes (`edad`, `promedio`, `asistencia_pct`) con mediana

In [80]:
# --- Respuesta del estudiante (C1) ---
# Crear df_limpio y realizar limpieza
df_limpio = df.copy()

# 1. Limpieza de texto y normalización para 'campus'
campus_mapping = {
    'slp centro': 'SLP Centro',
    'slp cntro': 'SLP Centro',
    'slp norte': 'SLP Norte',
    'matehuala': 'Matehuala'
}
df_limpio['campus'] = df_limpio['campus'].str.lower().str.strip().replace(campus_mapping)

# 2. Limpieza de texto y normalización para 'modalidad'
modalidad_mapping = {
    'escolarizada': 'Escolarizada',
    'escolar': 'Escolarizada',
    'mixta': 'Mixta',
    'mixta ': 'Mixta'
}
df_limpio['modalidad'] = df_limpio['modalidad'].str.lower().str.strip().replace(modalidad_mapping)

# 3. Eliminar duplicados por id_estudiante
df_limpio.drop_duplicates(subset=['id_estudiante'], keep='first', inplace=True)

# 4. Corregir rangos en promedio y asistencia_pct (0-100)
df_limpio['promedio'] = df_limpio['promedio'].clip(0, 100)
df_limpio['asistencia_pct'] = df_limpio['asistencia_pct'].clip(0, 100)

# 5. Corregir creditos_aprobados <= creditos_inscritos
df_limpio['creditos_aprobados'] = np.minimum(df_limpio['creditos_aprobados'], df_limpio['creditos_inscritos'])

# 6. Imputar faltantes (edad, promedio, asistencia_pct) con mediana
median_edad = df_limpio['edad'].median()
median_promedio = df_limpio['promedio'].median()
median_asistencia_pct = df_limpio['asistencia_pct'].median()

df_limpio['edad'] = df_limpio['edad'].fillna(median_edad)
df_limpio['promedio'] = df_limpio['promedio'].fillna(median_promedio)
df_limpio['asistencia_pct'] = df_limpio['asistencia_pct'].fillna(median_asistencia_pct)

In [81]:
# --- Respuesta del estudiante (C2) ---
# Mostrar df_limpio.head()
display(df_limpio.head())

   id_estudiante nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0  SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  SLP Centro  Escolarizada      92.0            86.0                  32                  31
2            203  María  20.5   SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0  SLP Centro         Mixta      85.0            88.0                  30                  29
4            205  Sofía  21.0   Matehuala  Escolarizada      83.0            87.0                  26                  25

In [82]:
# --- Respuesta del estudiante (C3) ---
# Verificación posterior de calidad de datos

print("Verificación de Faltantes en df_limpio:")
display(df_limpio.isnull().sum())

print("\nVerificación de Duplicados por 'id_estudiante' en df_limpio:")
duplicated_ids_limpio = df_limpio[df_limpio.duplicated(subset=['id_estudiante'], keep=False)]
display(duplicated_ids_limpio)
print(f"Total de filas duplicadas (incluyendo la primera aparición) después de limpieza: {len(duplicated_ids_limpio)}")

print("\nVerificación de Valores únicos para 'campus' en df_limpio (después de limpieza):")
display(df_limpio['campus'].unique())

print("\nVerificación de Valores únicos para 'modalidad' en df_limpio (después de limpieza):")
display(df_limpio['modalidad'].unique())

print("\nVerificación de 'promedio' fuera de rango (0-100) en df_limpio:")
display(df_limpio[(df_limpio['promedio'] < 0) | (df_limpio['promedio'] > 100)])

print("\nVerificación de 'asistencia_pct' fuera de rango (0-100) en df_limpio:")
display(df_limpio[(df_limpio['asistencia_pct'] < 0) | (df_limpio['asistencia_pct'] > 100)])

print("\nVerificación de error lógico: 'creditos_aprobados' > 'creditos_inscritos' en df_limpio:")
display(df_limpio[df_limpio['creditos_aprobados'] > df_limpio['creditos_inscritos']])

Verificación de Faltantes en df_limpio:

id_estudiante         0
nombre                0
edad                  0
campus                0
modalidad             0
promedio              0
asistencia_pct        0
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

Verificación de Duplicados por 'id_estudiante' en df_limpio:

Empty DataFrame
Columns: [id_estudiante, nombre, edad, campus, modalidad, promedio, asistencia_pct, creditos_inscritos, creditos_aprobados]
Index: []

Total de filas duplicadas (incluyendo la primera aparición) después de limpieza: 0

Verificación de Valores únicos para 'campus' en df_limpio (después de limpieza):

array(['SLP Centro', 'SLP Norte', 'Matehuala'], dtype=object)

Verificación de Valores únicos para 'modalidad' en df_limpio (después de limpieza):

array(['Escolarizada', 'Mixta'], dtype=object)

Verificación de 'promedio' fuera de rango (0-100) en df_limpio:

Empty DataFrame
Columns: [id_estudiante, nombre, edad, campus, modalidad, promedio, asistencia_pct, creditos_inscritos, creditos_aprobados]
Index: []

Verificación de 'asistencia_pct' fuera de rango (0-100) en df_limpio:

Empty DataFrame
Columns: [id_estudiante, nombre, edad, campus, modalidad, promedio, asistencia_pct, creditos_inscritos, creditos_aprobados]
Index: []

Verificación de error lógico: 'creditos_aprobados' > 'creditos_inscritos' en df_limpio:

Empty DataFrame
Columns: [id_estudiante, nombre, edad, campus, modalidad, promedio, asistencia_pct, creditos_inscritos, creditos_aprobados]
Index: []

### Respuesta breve del estudiante (C4)
¿Por qué conviene limpiar sobre una copia (`df_limpio`) y no sobre `df`?

**Respuesta:** Conviene limpiar sobre una copia (`df_limpio`) para preservar el DataFrame original (`df`) en su estado crudo. Esto es crucial por varias razones:

1.  **Auditoría y Trazabilidad:** Permite comparar los datos antes y después de la limpieza, lo cual es fundamental para auditar las transformaciones realizadas y asegurar que los cambios son correctos y deseados. Si se comete un error durante la limpieza, se puede volver al original sin perder información.
2.  **Validación y Verificación:** Facilita la validación de los procesos de limpieza, permitiendo verificar si las correcciones tuvieron el efecto esperado sin afectar la fuente de datos original.
3.  **Análisis Comparativo:** Posibilita realizar diferentes tipos de análisis o aplicar distintas estrategias de limpieza sin modificar la fuente principal, lo que es útil para experimentar y comparar resultados.
4.  **Integridad de Datos Originales:** Asegura que si otras partes del proyecto o futuros análisis requieren los datos sin procesar, estos estén disponibles y sin alteraciones.

# Actividad D. Filtración y transformación (20 puntos)

Con `df_limpio`:
1. Filtra `promedio < 80`
2. Filtra `campus == 'SLP Centro'` y `modalidad == 'Escolarizada'`
3. Crea `tasa_aprobacion = creditos_aprobados / creditos_inscritos`
4. Crea `riesgo_academico`:
   - Alto: `promedio < 70` o `asistencia_pct < 75`
   - Medio: `promedio < 80`
   - Bajo: otro caso
5. (Opcional) One-hot encoding de `modalidad`

In [83]:
# --- Respuesta del estudiante (D1) ---
# Filtros solicitados

# 1. Filtra promedio < 80
df_promedio_bajo = df_limpio[df_limpio['promedio'] < 80]
print("Estudiantes con promedio < 80:")
display(df_promedio_bajo)

# 2. Filtra campus == 'SLP Centro' y modalidad == 'Escolarizada'
df_slp_escolarizada = df_limpio[(df_limpio['campus'] == 'SLP Centro') & (df_limpio['modalidad'] == 'Escolarizada')]
print("\nEstudiantes de 'SLP Centro' en modalidad 'Escolarizada':")
display(df_slp_escolarizada)

Estudiantes con promedio < 80:

   id_estudiante  nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
2            203   María  20.5   SLP Norte         Mixta      75.0            80.0                  28                  27
6            207  Carmen  20.0   Matehuala         Mixta      68.0            74.0                  24                  22
7            208    Joel  23.0  SLP Centro  Escolarizada      71.0            77.0                  30                  28
9            210  Andrés  20.0  SLP Centro  Escolarizada      79.0           100.0                  28                  28

Estudiantes de 'SLP Centro' en modalidad 'Escolarizada':

   id_estudiante  nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201   Laura  19.0  SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202    Iván  20.0  SLP Centro  Escolarizada      92.0            86.0                  32                  31
7            208    Joel  23.0  SLP Centro  Escolarizada      71.0            77.0                  30                  28
9            210  Andrés  20.0  SLP Centro  Escolarizada      79.0           100.0                  28                  28

In [84]:
# --- Respuesta del estudiante (D2) ---
# Crear tasa_aprobacion y riesgo_academico

# 3. Crea tasa_aprobacion = creditos_aprobados / creditos_inscritos
df_limpio['tasa_aprobacion'] = df_limpio['creditos_aprobados'] / df_limpio['creditos_inscritos']

# 4. Crea riesgo_academico:
#    - Alto: promedio < 70 o asistencia_pct < 75
#    - Medio: promedio < 80
#    - Bajo: otro caso
conditions = [
    (df_limpio['promedio'] < 70) | (df_limpio['asistencia_pct'] < 75),
    (df_limpio['promedio'] < 80)
]
choices = ['Alto', 'Medio']
df_limpio['riesgo_academico'] = np.select(conditions, choices, default='Bajo')

# 5. (Opcional) One-hot encoding de modalidad
# Aunque es opcional, lo incluiremos para mostrar cómo se hace.
df_limpio = pd.get_dummies(df_limpio, columns=['modalidad'], prefix='modalidad', dtype=int)

In [85]:
# --- Respuesta del estudiante (D3) ---
# Mostrar evidencia de transformación
print("DataFrame después de crear 'tasa_aprobacion' y 'riesgo_academico' y One-Hot Encoding de 'modalidad':")
display(df_limpio.head())

print("\nDistribución de 'riesgo_academico':")
display(df_limpio['riesgo_academico'].value_counts())

print("\nColumnas del DataFrame después del One-Hot Encoding de 'modalidad':")
display(df_limpio.columns)

DataFrame después de crear 'tasa_aprobacion' y 'riesgo_academico' y One-Hot Encoding de 'modalidad':

,id_estudiante,nombre,edad,campus,promedio,asistencia_pct,creditos_inscritos,creditos_aprobados,tasa_aprobacion,riesgo_academico,modalidad_Escolarizada,modalidad_Mixta
0,201,Laura,19.0,SLP Centro,87.0,93.0,30,29,0.966667,Bajo,1,0
1,202,Iván,20.0,SLP Centro,92.0,86.0,32,31,0.968750,Bajo,1,0
2,203,María,20.5,SLP Norte,75.0,80.0,28,27,0.964286,Medio,0,1
3,204,Diego,22.0,SLP Centro,85.0,88.0,30,29,0.966667,Bajo,0,1
4,205,Sofía,21.0,Matehuala,83.0,87.0,26,25,0.961538,Bajo,1,0

Distribución de 'riesgo_academico':

riesgo_academico
Bajo     7
Medio    3
Alto     1
Name: count, dtype: int64

Columnas del DataFrame después del One-Hot Encoding de 'modalidad':

Index(['id_estudiante', 'nombre', 'edad', 'campus', 'promedio', 'asistencia_pct', 'creditos_inscritos', 'creditos_aprobados',
       'tasa_aprobacion', 'riesgo_academico', 'modalidad_Escolarizada', 'modalidad_Mixta'],
      dtype='object')

### Respuesta breve del estudiante (D4)
¿Cuál es la diferencia entre **filtrar** y **transformar** datos?

**Respuesta:**

-   **Filtración (Filtering):** La filtración de datos implica seleccionar un subconjunto de filas (observaciones) de un DataFrame que cumplen con una o más condiciones específicas. Esencialmente, se eliminan las filas que no son relevantes para el análisis actual, pero las columnas y la estructura de las filas restantes no cambian. El objetivo es reducir el volumen de datos o enfocarse en un grupo particular de observaciones.
    *   **Ejemplo:** Seleccionar solo a los estudiantes con un promedio menor a 80, o aquellos que pertenecen a un campus específico.

-   **Transformación (Transformation):** La transformación de datos implica modificar la estructura o los valores de las columnas (variables) existentes, o crear nuevas columnas a partir de las existentes. No se eliminan filas, sino que se alteran los datos para hacerlos más adecuados para el análisis, para normalizarlos, para derivar nuevas características, o para cambiar su tipo de dato.
    *   **Ejemplo:** Calcular la `tasa_aprobacion` (una nueva columna), categorizar el `riesgo_academico` (modificar valores o crear una nueva columna), o aplicar One-Hot Encoding a una columna categórica como `modalidad` (crear nuevas columnas binarias).

# Actividad E. Fusión (`merge`) y resumen final (15 puntos)

1. Une `df_limpio` con `apoyos` por `id_estudiante` con `how='left'` e `indicator=True`
2. Guarda en `df_final`
3. Muestra `shape` y conteo de `_merge`
4. Resume:
   - promedio general
   - promedio por `campus`
   - distribución de `riesgo_academico`
5. Guarda CSV en `salida_eval/estudiantes_preprocesados_eval.csv`

In [86]:
# --- Respuesta del estudiante (E1) ---
# Merge y creación de df_final

# 1. Une df_limpio con apoyos por id_estudiante con how='left' e indicator=True
df_final = pd.merge(df_limpio, apoyos, on='id_estudiante', how='left', indicator=True)

# 2. Guarda en df_final (ya hecho en el paso anterior)

print("DataFrame Final (df_final) creado.")
print("Shape de df_final:", df_final.shape)
print("\nConteo de la columna '_merge':")
display(df_final['_merge'].value_counts())

DataFrame Final (df_final) creado.
Shape de df_final: (11, 15)

Conteo de la columna '_merge':

_merge
both          6
left_only     5
right_only    0
Name: count, dtype: int64

In [87]:
# --- Respuesta del estudiante (E2) ---
# Resumen final

print("--- Resumen Final ---")

# Promedio general
print("\nPromedio general de 'promedio':")
display(df_final['promedio'].mean())

# Promedio por campus
print("\nPromedio de 'promedio' por campus:")
display(df_final.groupby('campus')['promedio'].mean())

# Distribución de riesgo_academico
print("\nDistribución de 'riesgo_academico':")
display(df_final['riesgo_academico'].value_counts())

--- Resumen Final ---

Promedio general de 'promedio':

np.float64(83.9090909090909)

Promedio de 'promedio' por campus:

campus
Matehuala     75.500000
SLP Centro    83.666667
SLP Norte     90.000000
Name: promedio, dtype: float64

Distribución de 'riesgo_academico':

riesgo_academico
Bajo     7
Medio    3
Alto     1
Name: count, dtype: int64

In [88]:
# --- Respuesta del estudiante (E3) ---
# Guardar archivo final en CSV

# Asegurar que el directorio de salida exista
Path("salida_eval").mkdir(exist_ok=True)

# Guardar df_final a CSV
df_final.to_csv("salida_eval/estudiantes_preprocesados_eval.csv", index=False)

print("DataFrame final guardado exitosamente en 'salida_eval/estudiantes_preprocesados_eval.csv' ✅")

DataFrame final guardado exitosamente en 'salida_eval/estudiantes_preprocesados_eval.csv' ✅

# Actividad F. Reflexión final (5 puntos)

Responde brevemente:
1. ¿Qué error fue más frecuente?
2. ¿Qué corrección fue más importante para evitar errores de análisis?
3. ¿Qué pasaría si este dataset se usa sin limpiar?

**Respuestas:**

1.  **Error más frecuente:** Los errores más frecuentes fueron la **inconsistencia en los valores categóricos** (diferentes grafías, mayúsculas/minúsculas, espacios en `campus` y `modalidad`) y los **valores faltantes**. Estos problemas estaban dispersos en varias columnas y requerían un tratamiento estandarizado para asegurar la uniformidad de los datos.

2.  **Corrección más importante para evitar errores de análisis:** La corrección más importante fue la **normalización de los valores categóricos (`campus` y `modalidad`) y la eliminación de duplicados por `id_estudiante`**. Sin una estandarización de las categorías, un análisis que agrupara por `campus` o `modalidad` daría resultados incorrectos al tratar, por ejemplo, "SLP Centro" y "slp centro " como categorías distintas. La eliminación de duplicados es fundamental para evitar la sobreestimación de registros y asegurar que cada observación represente una entidad única.

3.  **¿Qué pasaría si este dataset se usa sin limpiar?** Si el dataset se usara sin limpiar, se presentarían varios problemas:
    *   **Análisis incorrectos:** Las inconsistencias en los datos llevarían a conteos, promedios y distribuciones erróneas (ej. múltiples 'SLP Centro' en estadísticas de campus). Los valores faltantes sesgarían o impedirían ciertos cálculos. Los valores fuera de rango o lógicamente imposibles (promedio > 100, créditos aprobados > inscritos) distorsionarían las métricas y conclusiones.
    *   **Modelos de Machine Learning ineficaces:** Los algoritmos de ML sufrirían de ruido, sesgos y un rendimiento deficiente, ya que no podrían interpretar correctamente los datos inconsistentes, incompletos o erróneos.
    *   **Decisiones empresariales erróneas:** Basar decisiones en datos no limpios podría llevar a estrategias ineficientes, asignación incorrecta de recursos o una comprensión equivocada de la situación actual (ej. identificar mal a los estudiantes en riesgo o las necesidades de apoyo).

## Lista de cotejo antes de entregar
- [x] Corrí todas las celdas en orden
- [x] Mi código no produce errores
- [x] Mostré evidencia de cada actividad
- [x] Creé `df_limpio` y `df_final`
- [x] Guardé el CSV final
- [x] Respondí las preguntas breves

## Apéndice (recordatorio rápido de funciones útiles)
`read_csv`, `shape`, `head`, `info`, `describe`, `isna`, `duplicated`, `drop_duplicates`,
`str.strip`, `str.lower`, `map`, `clip`, `fillna`, `np.minimum`, filtros booleanos, `np.select`,
`get_dummies`, `merge`, `to_csv`

## Observaciones del docente (uso exclusivo del profesor)
- Puntuación:
- Fortalezas:
- Áreas de mejora:
- Recomendación: