 datos casas india

ActividadesLab

1. Crear un Dataframe.

2. Dar toda la información.

3. Crear una máscara y van a filtrar por precio ›= 10,000

4. ¿Cuántas son inferiores a 10,000?

5. Crear un nuevo Dataframe a partir de los valores >= 10000

6. Dar toda la información.

7. Crear una serie con todas las direcciones de las casas

In [2]:
#crear un dataframe
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
datos_casa_india = pd.read_csv("/content/datos_casa_india/datos_casas_india.csv", index_col=0)
datos_casa_india.head()

,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
house_type,,,,,,,,,,,,,,,
1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
2 BHK Independent Floor,500 sq ft,Uttam Nagar,Delhi,28.618677,77.053352,8500,INR,1.0,NaN,NaN,NaN,Posted 12 days ago,"Zero Brokerage.\r\n\r\n2 Room set, Govt bijali...",No Deposit,Semi-Furnished
3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished

In [9]:
display(datos_casa_india) #dar toda la informacion

,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
house_type,,,,,,,,,,,,,,,
1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
2 BHK Independent Floor,500 sq ft,Uttam Nagar,Delhi,28.618677,77.053352,8500,INR,1.0,NaN,NaN,NaN,Posted 12 days ago,"Zero Brokerage.\r\n\r\n2 Room set, Govt bijali...",No Deposit,Semi-Furnished
3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4 BHK Villa,"5,896 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1022001,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its four bhk villa in the super location of De...,"40,10,102",Unfurnished
5 BHK Independent House,"6,521 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1549181,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,A 5 bhk property is available for rent in Sund...,"54,01,015",Unfurnished
3 BHK Independent Floor,"1,855 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"18,18,181",Unfurnished
3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301011,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,110",Unfurnished
3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,182",Unfurnished

In [10]:
datos_casa_india.shape # para ver todo el contenido (comprobar)

(5000, 15)

In [ ]:
#crear una mascara y filtrar por precio los que sean igual o mayores de 10,000

In [12]:
mask_precio = datos_casa_india['price'] >= 10000
datos_casa_india_filtrado = datos_casa_india[mask_precio]
display(datos_casa_india_filtrado)

,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
house_type,,,,,,,,,,,,,,,
1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
3 BHK Apartment,750 sq ft,DLF Farms,Delhi,28.488153,77.156975,11000,INR,1.0,NaN,NaN,NaN,Posted 2 years ago,Well designed 3 bhk multistorey apartment is a...,No Deposit,Semi-Furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4 BHK Villa,"5,896 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1022001,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its four bhk villa in the super location of De...,"40,10,102",Unfurnished
5 BHK Independent House,"6,521 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1549181,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,A 5 bhk property is available for rent in Sund...,"54,01,015",Unfurnished
3 BHK Independent Floor,"1,855 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"18,18,181",Unfurnished
3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301011,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,110",Unfurnished
3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,182",Unfurnished

In [13]:
#cuantas son inferiores a 10,000
mask_precio = datos_casa_india['price'] <= 10000
datos_casa_india_filtrado = datos_casa_india[mask_precio]
display(datos_casa_india_filtrado)

,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
house_type,,,,,,,,,,,,,,,
2 BHK Independent Floor,500 sq ft,Uttam Nagar,Delhi,28.618677,77.053352,8500,INR,1.0,NaN,NaN,NaN,Posted 12 days ago,"Zero Brokerage.\r\n\r\n2 Room set, Govt bijali...",No Deposit,Semi-Furnished
2 BHK Apartment,"1,162 sq ft",Gagan Vihar,Delhi,28.708557,77.328026,10000,INR,2.0,NaN,NaN,NaN,Posted a month ago,24 Hour's Ground Water Supply Available\r\nSta...,No Deposit,Semi-Furnished
1 BHK Independent Floor,700 sq ft,Uttam Nagar,Delhi,28.619457,77.056709,8500,INR,1.0,NaN,NaN,NaN,Posted a month ago,This is a well-designed 1 BHK Independent Floo...,No Deposit,Semi-Furnished
1 BHK Independent Floor,360 sq ft,Badarpur,Delhi,28.491892,77.306938,8000,INR,1.0,NaN,NaN,NaN,Posted 3 years ago,This spacious 1 bhk builder floor is available...,No Deposit,Unfurnished
2 BHK Apartment,480 sq ft,Uttam Nagar,Delhi,28.618303,77.056946,6500,INR,1.0,NaN,NaN,NaN,Posted 4 years ago,NaN,No Deposit,Semi-Furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2 BHK Independent House,445 sq ft,Burari,Delhi,28.760500,77.188286,5500,INR,1.0,NaN,Negotiable,NaN,Posted a year ago,This spacious 2 bhk independent house is avail...,"5,000",Unfurnished
2 BHK Apartment,"1,800 sq ft",Uttam Nagar,Delhi,28.618809,77.058998,9000,INR,1.0,1.0,Negotiable,NaN,Posted a year ago,2 BHK 3rd flr front side with lift with bike p...,"9,000",Semi-Furnished
1 BHK Independent Floor,500 sq ft,Saket,Delhi,28.523548,77.200142,8000,INR,1.0,NaN,Negotiable,NaN,Posted a year ago,This spacious 1 bhk builder floor is available...,"8,000",Semi-Furnished
1 BHK Independent House,333 sq ft,dda flat,Delhi,28.655981,77.311623,4500,INR,1.0,1.0,NaN,NaN,Posted a year ago,It has area of 333 sqft and is available at a ...,"4,500",Semi-Furnished
1 BHK Apartment,450 sq ft,Nawada,Delhi,28.627590,77.028709,5500,INR,1.0,1.0,NaN,NaN,Posted a year ago,Well designed 1 bhk multistorey apartment is a...,"5,500",Semi-Furnished

In [21]:
#crear nuevo data frame  a partir de los valores mayores o igules que 10,000
# 5. Crear nuevo DataFrame filtrado
df_nuevo = datos_casa_india[mask_precio_alto].copy()

In [23]:
# 7. Crear una serie con las direcciones
serie_direcciones = df_nuevo['location']

# Mostrar los resultados
display(serie_direcciones)

house_type
1 RK Studio Apartment                  Kalkaji
1 RK Studio Apartment        Mansarover Garden
3 BHK Independent House             Model Town
2 BHK Apartment               Sector 13 Rohini
3 BHK Apartment                      DLF Farms
                                   ...
4 BHK Villa                       Sunder Nagar
5 BHK Independent House           Sunder Nagar
3 BHK Independent Floor     New Friends Colony
3 BHK Independent Floor     New Friends Colony
3 BHK Independent Floor     New Friends Colony
Name: location, Length: 4827, dtype: object

In [ ]:
#crear una serie con todas las direcciones de las casas

In [24]:
serie_todas_direcciones = datos_casa_india['location']
display(serie_todas_direcciones)

house_type
1 RK Studio Apartment                  Kalkaji
1 RK Studio Apartment        Mansarover Garden
2 BHK Independent Floor            Uttam Nagar
3 BHK Independent House             Model Town
2 BHK Apartment               Sector 13 Rohini
                                   ...
4 BHK Villa                       Sunder Nagar
5 BHK Independent House           Sunder Nagar
3 BHK Independent Floor     New Friends Colony
3 BHK Independent Floor     New Friends Colony
3 BHK Independent Floor     New Friends Colony
Name: location, Length: 5000, dtype: object

vicente, david adan y edgar moctezuma.